# Generated by Django 2.1.4 on 2018-12-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Math',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(max_length=3)),
                ('arg1', models.IntegerField()),
                ('arg2', models.IntegerField()),
            ],
        ),
    ]
